# Change these first
owner: phimado # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: SRV01 Web
    check: "tcp-ping"
    url: 89.22.112.170
    port: 443
  - name: SRV01 Mail
    check: "tcp-ping"
    url: 89.22.112.170
    port: 993
  - name: PHIMADO
    url: https://phimado.de
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
  - name: ECDC
    url: https://memmingen-indians.de
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
  - name: ECDC Shop
    url: https://shop.memmingen-indians.de
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.phimado.de
  theme: night
  # baseUrl: /status
  logoUrl: https://cdn.phimado.de/2021/01/phimado_logo_hell.svg
  name: PHIMADO Service Status
  navbar:
    - title: Status
      href: /
    - title: PHIMADO
      href: https://phimado.de
  metaTags:
    - name: "robots"
      content: "noindex"

  i18n:
    activeIncidents: Aktive Incidents
    allSystemsOperational: Alle System sind online
    incidentReport: "Incident #$NUMBER report →"
    activeIncidentSummary: Geöffnet am $DATE mit $POSTS posts
    incidentTitle: Incident $NUMBER Details
    incidentDetails: Incident Details
    incidentFixed: Fixed
    incidentOngoing: Ongoing
    incidentOpenedAt: Geöffnet um
    incidentClosedAt: Geschlossen um
    incidentViewOnGitHub: View and Subscribe on GitHub
    incidentCommentSummary: Gepostet am $DATE von $AUTHOR
    incidentBack: ← Zurück zu allen Incidents
    pastIncidents: Letzte Incidents
    pastIncidentsResolved: Resolved in $MINUTES Minuten mit $POSTS posts
    liveStatus: Live Status
    overallUptime: "Verfügbarkeit: $UPTIME"
    overallUptimeTitle: Verfügbarkeit
    averageResponseTime: "Durchschnittliche Antwort-Zeit: $TIMEms"
    averageResponseTimeTitle: Durchschnittliche Antwort-Zeit
    sevelDayResponseTime: 7-Tages Antwort-Zeit
    responseTimeMs: Antwort-Zeit (ms)
    up: Up
    down: Down
    degraded: Degraded
    ms: ms
    loading: Lädt
    navGitHub: GitHub
    footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
    rateLimitExceededTitle: Rate limit exceeded
    rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
    rateLimitExceededWhatDoesErrorMean: What does this error mean?
    rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
    rateLimitExceededErrorHowCanFix: How can I fix it?
    rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
    rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
    rateLimitExceededHasSet: You have a personal access token set.
    rateLimitExceededRemoveToken: Remove token
    rateLimitExceededGitHubPAT: GitHub Personal Access Token
    rateLimitExceededCopyPastePAT: Copy and paste your token
    rateLimitExceededSaveToken: Save token
    errorTitle: An error occurred
    errorIntro: An error occurred in trying to get the latest status details.
    errorText: You can try again in a few moments.
    errorHome: Go to the homepage
    pastScheduledMaintenance: Past Scheduled Maintenance
    scheduledMaintenance: Scheduled Maintenance
    scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
    scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
    startedAt: Begonnen um
    startsAt: Beginnt um
    duration: Dauer
    durationMin: $DURATION Minuten
    incidentCompleted: Abgeschlossen
    incidentScheduled: Angelegt
    duration24H: 24h
    duration7D: 7d
    duration30D: 30d
    duration1Y: 1y
    durationAll: Alle
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
