# Change these first
owner: phimado # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: SRV01 Web
    check: "tcp-ping"
    url: 89.22.112.170
    port: 443
  - name: SRV01 Mail
    check: "tcp-ping"
    url: 89.22.112.170
    port: 993
  - name: PHIMADO
    url: https://phimado.de
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
  - name: ECDC
    url: https://memmingen-indians.de
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
  - name: ECDC Shop
    url: https://shop.memmingen-indians.de
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
  - name: Test
    url: https://shosp.memmingen-indians.de
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.phimado.de
  theme: night
  # baseUrl: /status
  logoUrl: https://cdn.phimado.de/2021/01/phimado_logo_hell.svg
  name: PHIMADO Service Status
  navbar:
    - title: Status
      href: /
    - title: PHIMADO
      href: https://phimado.de
  metaTags:
    - name: "robots"
      content: "noindex"
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
